### ISSUE TITLE
Comments

### ISSUE THREAD

**Issue by JaninaPi** [raspberrypilearning/pi-tag#1]
- The resource isn't super friendly for people who don't want to buy the Monk Makes kit (regarding use of the RFID reader)
- line 34 in step 8 is missing a `.strip()`, I think.

**Comment by MarcScott** [comment]
1. Unfortunately it's probably the simplest way to get up and running with RFID. I'm planning to buy a few generic ones and when I get around to it I'll update this resource with some other options.
2. Good spot - I've fixed it.
